# Generated by Django 6.0 on 2026-01-03 17:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "setting_key",
                    models.CharField(
                        help_text="e.g., 'monthly_publication_day', 'min_questions_for_featured'",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "setting_value",
                    models.TextField(help_text="JSON string or simple value"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What this setting controls", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App Setting",
                "verbose_name_plural": "App Settings",
                "db_table": "app_settings",
                "ordering": ["setting_key"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Branch name in English", max_length=255, unique=True
                    ),
                ),
                (
                    "name_np",
                    models.CharField(help_text="Branch name in Nepali", max_length=255),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_np", models.TextField(blank=True, null=True)),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="branch_icons/"),
                ),
                (
                    "has_sub_branches",
                    models.BooleanField(
                        default=False,
                        help_text="Does this branch have specializations?",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order for displaying in UI"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "db_table": "branches",
                "ordering": ["display_order", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=255)),
                ("name_np", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_np", models.TextField(blank=True, null=True)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("UNIVERSAL", "Universal - All Branches"),
                            ("BRANCH", "Branch Specific"),
                            ("SUBBRANCH", "Sub-Branch Specific"),
                        ],
                        help_text="Defines where this category applies",
                        max_length=20,
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General - Common across branches"),
                            ("SPECIAL", "Special - Technical/Specialized"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Premade categories are public"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="category_icons/"
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="Hex color for UI (e.g., #FF5733)",
                        max_length=7,
                        null=True,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="null for system/admin created categories",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required if scope is BRANCH or SUBBRANCH",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="src.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "ordering": ["display_order", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="DailyActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date of activity tracking", unique=True
                    ),
                ),
                (
                    "new_users",
                    models.IntegerField(default=0, help_text="New user registrations"),
                ),
                (
                    "questions_added",
                    models.IntegerField(
                        default=0, help_text="New questions added this day"
                    ),
                ),
                (
                    "questions_approved",
                    models.IntegerField(
                        default=0, help_text="Questions approved by admins"
                    ),
                ),
                (
                    "mock_tests_taken",
                    models.IntegerField(default=0, help_text="Tests started this day"),
                ),
                (
                    "total_answers_submitted",
                    models.IntegerField(
                        default=0, help_text="Question attempts across all users"
                    ),
                ),
                (
                    "active_users",
                    models.IntegerField(
                        default=0, help_text="Unique users who performed any action"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Daily Activity",
                "verbose_name_plural": "Daily Activities",
                "db_table": "daily_activities",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="daily_activ_date_8b6efd_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="MockTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(max_length=255)),
                ("title_np", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_np", models.TextField(blank=True, null=True)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("OFFICIAL", "Official PSC Pattern"),
                            ("COMMUNITY", "Community Created"),
                            ("CUSTOM", "User Custom Test"),
                        ],
                        default="COMMUNITY",
                        max_length=20,
                    ),
                ),
                (
                    "total_questions",
                    models.IntegerField(help_text="Total number of questions in test"),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="If null, user can set their own timing",
                        null=True,
                    ),
                ),
                (
                    "use_standard_duration",
                    models.BooleanField(
                        default=True, help_text="Use TimeConfiguration or custom timing"
                    ),
                ),
                (
                    "pass_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=40.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "attempt_count",
                    models.IntegerField(
                        default=0, help_text="Total attempts by all users"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mock_tests",
                        to="src.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="null for official tests",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_mock_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mock Test",
                "verbose_name_plural": "Mock Tests",
                "db_table": "mock_tests",
            },
        ),
        migrations.CreateModel(
            name="PlatformStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_questions_public",
                    models.IntegerField(
                        default=0, help_text="All approved public questions"
                    ),
                ),
                (
                    "total_questions_pending",
                    models.IntegerField(
                        default=0, help_text="Waiting for monthly approval"
                    ),
                ),
                (
                    "total_contributions_this_month",
                    models.IntegerField(
                        default=0,
                        help_text="Contributions in current month (resets monthly)",
                    ),
                ),
                (
                    "total_users_active",
                    models.IntegerField(
                        default=0,
                        help_text="Users who contributed/attempted in last 30 days",
                    ),
                ),
                (
                    "total_mock_tests_taken",
                    models.IntegerField(default=0, help_text="All time test attempts"),
                ),
                (
                    "total_answers_submitted",
                    models.IntegerField(
                        default=0, help_text="Total question attempts across platform"
                    ),
                ),
                (
                    "questions_added_today",
                    models.IntegerField(
                        default=0, help_text="Questions added in last 24 hours"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "most_attempted_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="top_category_stats",
                        to="src.category",
                    ),
                ),
                (
                    "top_contributor_this_month",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="top_contributor_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Statistics",
                "verbose_name_plural": "Platform Statistics",
                "db_table": "platform_stats",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text_en", models.TextField(help_text="Question in English")),
                ("question_text_np", models.TextField(help_text="Question in Nepali")),
                (
                    "difficulty_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        help_text="Required only for IQ & Mathematics categories",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[("MCQ", "Multiple Choice Question")],
                        default="MCQ",
                        max_length=20,
                    ),
                ),
                (
                    "explanation_en",
                    models.TextField(
                        help_text="Detailed explanation for correct answer in English"
                    ),
                ),
                (
                    "explanation_np",
                    models.TextField(help_text="Detailed explanation in Nepali"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional diagram or chart",
                        null=True,
                        upload_to="question_images/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("PUBLIC", "Public"),
                            ("PRIVATE", "Private"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "consent_given",
                    models.BooleanField(
                        default=False, help_text="User agreed to make question public"
                    ),
                ),
                (
                    "scheduled_public_date",
                    models.DateField(
                        blank=True,
                        help_text="When question becomes public (monthly batch)",
                        null=True,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'PSC 2078 Nasu Exam'",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "times_attempted",
                    models.IntegerField(
                        default=0,
                        help_text="How many times this question was attempted",
                    ),
                ),
                (
                    "times_correct",
                    models.IntegerField(
                        default=0, help_text="How many times answered correctly"
                    ),
                ),
                (
                    "reported_count",
                    models.IntegerField(
                        default=0, help_text="Number of quality reports filed"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Admin verified quality"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Single category assignment",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="src.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who contributed this question",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contributed_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("CONTRIBUTION_APPROVED", "Contribution Approved"),
                            ("QUESTION_PUBLIC", "Question Made Public"),
                            ("LEADERBOARD_RANK", "Leaderboard Rank Change"),
                            ("REPORT_RESOLVED", "Report Resolved"),
                            ("STREAK_ALERT", "Streak Alert"),
                            ("MILESTONE", "Milestone Achieved"),
                            ("GENERAL", "General Notification"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="Notification heading in English", max_length=255
                    ),
                ),
                (
                    "title_np",
                    models.CharField(
                        help_text="Notification heading in Nepali", max_length=255
                    ),
                ),
                (
                    "message_en",
                    models.TextField(help_text="Notification body in English"),
                ),
                (
                    "message_np",
                    models.TextField(help_text="Notification body in Nepali"),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="Deep link for mobile app navigation",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_mock_test",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="src.mocktest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_question",
                    models.ForeignKey(
                        blank=True,
                        help_text="If notification is about a specific question",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="src.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MockTestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_order",
                    models.IntegerField(help_text="Sequence number in the test"),
                ),
                (
                    "marks_allocated",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Marks for this question in this test",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mock_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_questions",
                        to="src.mocktest",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mock_test_appearances",
                        to="src.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mock Test Question",
                "verbose_name_plural": "Mock Test Questions",
                "db_table": "mock_test_questions",
                "ordering": ["mock_test", "question_order"],
            },
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contribution_month",
                    models.IntegerField(
                        help_text="Month of contribution (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "contribution_year",
                    models.IntegerField(help_text="Year of contribution"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("MADE_PUBLIC", "Made Public"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Selected for Facebook shoutout"
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the contribution was approved",
                        null=True,
                    ),
                ),
                (
                    "public_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When made available to all users",
                        null=True,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="If rejected, explanation why", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contribution_records",
                        to="src.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contribution",
                "verbose_name_plural": "Contributions",
                "db_table": "contributions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_text_en",
                    models.TextField(help_text="Answer option in English"),
                ),
                (
                    "answer_text_np",
                    models.TextField(help_text="Answer option in Nepali"),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False,
                        help_text="Only one answer should be True per question",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order for A, B, C, D display"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="src.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
                "db_table": "answers",
                "ordering": ["question", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="QuestionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("INCORRECT_ANSWER", "Incorrect Answer"),
                            ("TYPO", "Typo/Grammar Error"),
                            ("INAPPROPRIATE", "Inappropriate Content"),
                            ("DUPLICATE", "Duplicate Question"),
                            ("OTHER", "Other Issue"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed explanation of the issue"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("RESOLVED", "Resolved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about resolution",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the report was resolved", null=True
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="src.question",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin or moderator who reviewed this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Report",
                "verbose_name_plural": "Question Reports",
                "db_table": "question_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Collection name (e.g., 'My Weak Questions', 'Math Practice')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What this collection is for", null=True
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=True, help_text="Personal vs shareable collections"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier for UI",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="Hex color for UI (e.g., #FF5733)",
                        max_length=7,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="User's curated question list",
                        related_name="study_collections",
                        to="src.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Collection",
                "verbose_name_plural": "Study Collections",
                "db_table": "study_collections",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SubBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=255)),
                ("name_np", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_np", models.TextField(blank=True, null=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="subbranch_icons/"
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_branches",
                        to="src.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Branch",
                "verbose_name_plural": "Sub Branches",
                "db_table": "sub_branches",
                "ordering": ["branch", "display_order", "name_en"],
            },
        ),
        migrations.AddField(
            model_name="mocktest",
            name="sub_branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional for branch-only tests",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mock_tests",
                to="src.subbranch",
            ),
        ),
        migrations.CreateModel(
            name="LeaderBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_period",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("ALL_TIME", "All Time"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rank", models.IntegerField(help_text="Current ranking position")),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sum of all test scores in this period",
                        max_digits=10,
                    ),
                ),
                (
                    "tests_completed",
                    models.IntegerField(
                        default=0, help_text="Number of tests completed in this period"
                    ),
                ),
                (
                    "accuracy_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Overall accuracy in this period",
                        max_digits=5,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="src.branch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sub_branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leaderboard can be branch-wide or sub-branch specific",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="src.subbranch",
                    ),
                ),
            ],
            options={
                "verbose_name": "LeaderBoard Entry",
                "verbose_name_plural": "LeaderBoard Entries",
                "db_table": "leaderboards",
                "ordering": ["time_period", "branch", "rank"],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="target_sub_branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Required only if scope is SUBBRANCH",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="src.subbranch",
            ),
        ),
        migrations.CreateModel(
            name="TimeConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "standard_duration_minutes",
                    models.IntegerField(help_text="Official time limit in minutes"),
                ),
                (
                    "questions_count",
                    models.IntegerField(
                        help_text="Standard number of questions for this configuration"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Context about this configuration (e.g., 'PSC 2078 Pattern')",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_configs",
                        to="src.branch",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific category timing (e.g., IQ gets more time)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_configs",
                        to="src.category",
                    ),
                ),
                (
                    "sub_branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Branch-wide or sub-branch specific timing",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_configs",
                        to="src.subbranch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Configuration",
                "verbose_name_plural": "Time Configurations",
                "db_table": "time_configurations",
                "ordering": ["branch", "sub_branch", "category"],
            },
        ),
        migrations.CreateModel(
            name="UserAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When user started the attempt",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, help_text="When completed/submitted", null=True
                    ),
                ),
                (
                    "total_time_taken",
                    models.IntegerField(
                        blank=True,
                        help_text="Total seconds spent (calculated on completion)",
                        null=True,
                    ),
                ),
                (
                    "score_obtained",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum possible score",
                        max_digits=7,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated on completion",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("MOCK_TEST", "Mock Test"),
                            ("PRACTICE", "Practice Mode"),
                        ],
                        default="MOCK_TEST",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mock_test",
                    models.ForeignKey(
                        blank=True,
                        help_text="null for practice mode",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_attempts",
                        to="src.mocktest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Attempt",
                "verbose_name_plural": "User Attempts",
                "db_table": "user_attempts",
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "time_taken_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Time spent on this specific question",
                        null=True,
                    ),
                ),
                ("is_skipped", models.BooleanField(default=False)),
                (
                    "is_marked_for_review",
                    models.BooleanField(
                        default=False, help_text="User flagged to revisit later"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Updated when user changes answer"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_responses",
                        to="src.question",
                    ),
                ),
                (
                    "selected_answer",
                    models.ForeignKey(
                        blank=True,
                        help_text="null if question was skipped",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_selections",
                        to="src.answer",
                    ),
                ),
                (
                    "user_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="src.userattempt",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Answer",
                "verbose_name_plural": "User Answers",
                "db_table": "user_answers",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Optional contact number",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("EN", "English"), ("NP", "Nepali")],
                        default="EN",
                        max_length=2,
                    ),
                ),
                (
                    "experience_points",
                    models.IntegerField(
                        default=0,
                        help_text="Points earned through contributions and practice",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=1, help_text="Calculated from experience points"
                    ),
                ),
                (
                    "total_contributions",
                    models.IntegerField(
                        default=0, help_text="Total questions contributed by user"
                    ),
                ),
                ("total_questions_attempted", models.IntegerField(default=0)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                (
                    "google_auth_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="What branch they're preparing for",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_users",
                        to="src.branch",
                    ),
                ),
                (
                    "target_sub_branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific specialization within branch",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_users",
                        to="src.subbranch",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions_attempted", models.IntegerField(default=0)),
                ("correct_answers", models.IntegerField(default=0)),
                (
                    "accuracy_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Auto-calculated from correct/attempted ratio",
                        max_digits=5,
                    ),
                ),
                (
                    "average_time_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Average time per question in this category",
                        null=True,
                    ),
                ),
                (
                    "last_attempted_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time user attempted question from this category",
                        null=True,
                    ),
                ),
                (
                    "weak_topics",
                    models.JSONField(
                        blank=True,
                        help_text="JSON array of specific sub-topics user struggles with",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="src.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Progress",
                "verbose_name_plural": "User Progress Records",
                "db_table": "user_progress",
            },
        ),
        migrations.CreateModel(
            name="UserStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "questions_contributed",
                    models.IntegerField(default=0, help_text="Lifetime contributions"),
                ),
                (
                    "questions_made_public",
                    models.IntegerField(default=0, help_text="Approved contributions"),
                ),
                (
                    "questions_answered",
                    models.IntegerField(
                        default=0,
                        help_text="Total questions attempted (practice + tests)",
                    ),
                ),
                (
                    "correct_answers",
                    models.IntegerField(default=0, help_text="Total correct answers"),
                ),
                (
                    "mock_tests_completed",
                    models.IntegerField(
                        default=0, help_text="Number of completed mock tests"
                    ),
                ),
                (
                    "study_streak_days",
                    models.IntegerField(
                        default=0, help_text="Current consecutive days active"
                    ),
                ),
                (
                    "longest_streak",
                    models.IntegerField(default=0, help_text="Personal best streak"),
                ),
                (
                    "last_activity_date",
                    models.DateField(
                        blank=True, help_text="Last date user was active", null=True
                    ),
                ),
                (
                    "badges_earned",
                    models.JSONField(
                        default=dict, help_text="Dictionary of achievement badges"
                    ),
                ),
                (
                    "contribution_rank",
                    models.IntegerField(
                        blank=True, help_text="Rank among all contributors", null=True
                    ),
                ),
                (
                    "accuracy_rank",
                    models.IntegerField(
                        blank=True, help_text="Rank by overall accuracy", null=True
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Statistics",
                "verbose_name_plural": "User Statistics",
                "db_table": "user_statistics",
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["category", "status"], name="questions_categor_f59c4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["is_public", "status"], name="questions_is_publ_7a5951_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["created_by", "status"], name="questions_created_dba25e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["scheduled_public_date"], name="questions_schedul_1a61aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="notificatio_user_id_a4dd5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "notification_type"],
                name="notificatio_user_id_63f199_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_e4c995_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mocktestquestion",
            unique_together={
                ("mock_test", "question"),
                ("mock_test", "question_order"),
            },
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(
                fields=["user", "status"], name="contributio_user_id_9def24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(
                fields=["contribution_year", "contribution_month"],
                name="contributio_contrib_caa61b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(
                fields=["status", "is_featured"], name="contributio_status_57f552_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contribution",
            unique_together={("user", "question")},
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("question", "display_order")},
        ),
        migrations.AddIndex(
            model_name="questionreport",
            index=models.Index(
                fields=["question", "status"], name="question_re_questio_3b4350_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionreport",
            index=models.Index(
                fields=["status", "created_at"], name="question_re_status_177d4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionreport",
            index=models.Index(
                fields=["reported_by"], name="question_re_reporte_679d7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studycollection",
            index=models.Index(
                fields=["created_by", "is_private"],
                name="study_colle_created_b8efd2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subbranch",
            unique_together={("branch", "slug")},
        ),
        migrations.AddIndex(
            model_name="mocktest",
            index=models.Index(
                fields=["branch", "sub_branch", "is_public"],
                name="mock_tests_branch__2d7c06_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mocktest",
            index=models.Index(
                fields=["test_type", "is_active"], name="mock_tests_test_ty_11c619_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboard",
            index=models.Index(
                fields=["time_period", "branch", "rank"],
                name="leaderboard_time_pe_b7e15d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboard",
            index=models.Index(
                fields=["user", "time_period"], name="leaderboard_user_id_d08d5f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leaderboard",
            unique_together={("user", "time_period", "branch", "sub_branch")},
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["scope_type", "is_public"], name="categories_scope_t_4d5033_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["target_branch", "target_sub_branch"],
                name="categories_target__081849_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timeconfiguration",
            index=models.Index(
                fields=["branch", "is_active"], name="time_config_branch__6f3604_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeconfiguration",
            index=models.Index(
                fields=["sub_branch", "is_active"],
                name="time_config_sub_bra_eb6bbd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userattempt",
            index=models.Index(
                fields=["user", "status"], name="user_attemp_user_id_8855f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userattempt",
            index=models.Index(
                fields=["mock_test", "status"], name="user_attemp_mock_te_9b7e47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userattempt",
            index=models.Index(
                fields=["created_at"], name="user_attemp_created_8cb7f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useranswer",
            index=models.Index(
                fields=["user_attempt", "is_correct"],
                name="user_answer_user_at_42a6df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useranswer",
            index=models.Index(
                fields=["question", "is_correct"], name="user_answer_questio_d3a0af_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together={("user_attempt", "question")},
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["email"], name="user_profil_email_8a1024_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["target_branch", "target_sub_branch"],
                name="user_profil_target__142d2c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["user", "accuracy_percentage"],
                name="user_progre_user_id_487980_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["category", "accuracy_percentage"],
                name="user_progre_categor_7f39a4_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userprogress",
            unique_together={("user", "category")},
        ),
        migrations.AddIndex(
            model_name="userstatistics",
            index=models.Index(
                fields=["contribution_rank"], name="user_statis_contrib_9215d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userstatistics",
            index=models.Index(
                fields=["accuracy_rank"], name="user_statis_accurac_78cd50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userstatistics",
            index=models.Index(
                fields=["study_streak_days"], name="user_statis_study_s_33a4af_idx"
            ),
        ),
    ]
