# Generated by Django 6.0 on 2026-01-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="previous_rank",
            field=models.IntegerField(
                blank=True, help_text="Rank from previous calculation", null=True
            ),
        ),
    ]
